Implement pure functional filters
codex-team/capella.scala pull request #1
Opened 2018-03-06 23:46 UTC by n0str

Now you can apply transformations

TODO: Docs
TODO: Comments to function

2018-03-07 08:23 UTC, n0str commented
Can use pipeline operator
`implicit class Pipe[A](a: A) extends AnyVal {
    def |>[B](f: A => B): B = f(a)
  }`

2018-03-08 10:35 UTC, talyguryn requested changes

2018-03-08 10:35 UTC, talyguryn commented on README.md
> +Currenty support all filters for CodeX Capella [https://github.com/codex-team/capella#filters](https://github.com/codex-team/capella#filters)
Очень странное предложение.

2018-03-08 10:35 UTC, talyguryn commented on src/main/scala/codex/capella/Filters.scala
> +
Тут есть пустые строки, а ниже нет. Как правильно?

2018-03-08 10:36 UTC, n0str commented on README.md
> +Currenty support all filters for CodeX Capella [https://github.com/codex-team/capella#filters](https://github.com/codex-team/capella#filters)
Напиши как считаешь правильным

2018-03-08 10:37 UTC, n0str commented on src/main/scala/codex/capella/Filters.scala
> +
Не очень понятно что ты предлагаешь. Мне кажется, что код читается нормально.

2018-03-09 08:01 UTC, talyguryn requested changes

2018-03-09 08:01 UTC, talyguryn commented on README.md
> +Currenty support all filters for CodeX Capella [https://github.com/codex-team/capella#filters](https://github.com/codex-team/capella#filters)
Зачем писать, что «на данный момент есть поддержка всех фильтров для кодекс капеллы». Тут плохо всё.
Почему нельзя сказать, мол, есть поддержка таких-то фильтров ... . О работе с фильтрами вы можете прочитать в [официальной документации](...)

2018-03-09 09:29 UTC, neSpecc approved these changes

2018-03-09 09:36 UTC, talyguryn approved these changes

2018-03-09 09:37 UTC, merged